### ISSUE TITLE
Select Keys at Current Time error

### ISSUE THREAD

**Issue by ARkaine2** [zlovatt/zl_Scriptlets#2]
I'm trying to use this script

https://raw.githubusercontent.com/zlovatt/zl_Scriptlets/master/Select%20Keys%20at%20Current%20Time.jsx

but AE sends me an error message:

Unable to execute script at line 93. After Effects error: Can not "set selected at key" with this property, because the property or a parent property is hidden.

**Comment by zlovatt** [comment]
This is fixed now~
